import { useState } from "react";
import { evidenceApi } from "../api/evidence";
import { MetricCard } from "../components/MetricCard";
import { Panel } from "../components/Panel";
import { ErrorState, LoadingState } from "../components/States";
import { EvidenceDetailPanel } from "../features/evidence/EvidenceDetailPanel";
import { AskEvidencePanel } from "../features/evidence/AskEvidencePanel";
import { useApi } from "../hooks/useApi";
import type { EvidenceRecordFilters } from "../types/evidence";
import { formatDate, formatNumber, formatPercent, titleCase } from "../utils/format";

const ORGANIZATION = "Wells Fargo";
const defaults: EvidenceRecordFilters = { limit: 25, offset: 0 };

export function EvidencePage() {
  const [selectedEvidence, setSelectedEvidence] = useState<string | null>(null);
  const [draft, setDraft] = useState({ search: "", source: "", technology: "", capability: "", location: "", enrichedOnly: false });
  const [filters, setFilters] = useState<EvidenceRecordFilters>(defaults);
  const summary = useApi((signal) => evidenceApi.summary(ORGANIZATION, signal), [ORGANIZATION]);
  const records = useApi((signal) => evidenceApi.records(ORGANIZATION, filters, signal), [ORGANIZATION, filters]);
  const applyFilters = () => setFilters({ limit: 25, offset: 0, search: draft.search || undefined, source: draft.source || undefined, technology: draft.technology || undefined, capability: draft.capability || undefined, location: draft.location || undefined, enriched: draft.enrichedOnly ? true : undefined });
  return <div className="page">
    <div className="page-heading"><div><span className="eyebrow">Evidence & Traceability</span><h1>Inspect the records supporting intelligence</h1><p>Review authoritative source evidence, model-derived enrichment, and deterministic intelligence relationships without conflating their provenance.</p></div><label className="organization-select"><span>Organization</span><select value={ORGANIZATION} disabled><option>Wells Fargo</option></select></label></div>
    {summary.loading && <LoadingState label="Loading evidence summary…" />}{summary.error && <ErrorState message={summary.error} />}
    {summary.data && <><div className="metrics-grid metrics-grid--four"><MetricCard icon="01" label="Evidence records" value={formatNumber(summary.data.total_evidence_records)} context={`${summary.data.total_jobs} represented jobs`} /><MetricCard icon="02" label="Source coverage" value={formatPercent(summary.data.evidence_coverage, 1)} context={`${summary.data.jobs_with_evidence} jobs with evidence`} /><MetricCard icon="03" label="Enriched records" value={formatNumber(summary.data.enriched_evidence_count)} context={`${formatPercent(summary.data.enrichment_coverage, 1)} of evidence records`} /><MetricCard icon="04" label="Signal-supporting evidence" value={formatNumber(summary.data.evidence_supporting_hiring_signals + summary.data.evidence_supporting_technology_signals)} context={`${summary.data.evidence_supporting_technology_observations} records support technology observations`} /></div><div className="context-strip"><span><strong>Observation period</strong>{formatDate(summary.data.observation_start)} – {formatDate(summary.data.observation_end)}</span><span><strong>Sources</strong>{summary.data.source_distribution.map((item) => `${item.source} (${item.evidence_count})`).join(" · ") || "No sources"}</span></div></>}
    <AskEvidencePanel organization={ORGANIZATION} onViewEvidence={setSelectedEvidence} />
    <Panel title="Evidence records" eyebrow="Source, enriched, and derived relationships" action={records.data ? <span className="result-count">{records.data.total} records</span> : undefined}>
      <div className="evidence-filters"><label><span>Search</span><input value={draft.search} onChange={(event) => setDraft({ ...draft, search: event.target.value })} placeholder="Job, evidence, technology" /></label><label><span>Source</span><input value={draft.source} onChange={(event) => setDraft({ ...draft, source: event.target.value })} placeholder="Workday" /></label><label><span>Technology</span><input value={draft.technology} onChange={(event) => setDraft({ ...draft, technology: event.target.value })} placeholder="Python" /></label><label><span>Capability</span><input value={draft.capability} onChange={(event) => setDraft({ ...draft, capability: event.target.value })} placeholder="Data & Analytics" /></label><label><span>Location</span><input value={draft.location} onChange={(event) => setDraft({ ...draft, location: event.target.value })} placeholder="Charlotte" /></label><label className="checkbox-filter"><input type="checkbox" checked={draft.enrichedOnly} onChange={(event) => setDraft({ ...draft, enrichedOnly: event.target.checked })} /><span>Enriched only</span></label><button className="primary-button" onClick={applyFilters}>Apply filters</button></div>
      {records.loading && <LoadingState label="Loading evidence records…" />}{records.error && <ErrorState message={records.error} />}{records.data?.items.length === 0 && <div className="inline-empty">No evidence records match the current filters.</div>}
      {records.data && records.data.items.length > 0 && <><div className="table-wrap"><table><thead><tr><th>Evidence</th><th>Job</th><th>Source</th><th>Location</th><th>Enrichment</th><th>Intelligence links</th><th>Captured</th></tr></thead><tbody>{records.data.items.map((item) => <tr key={item.evidence_id}><td><button className="job-title-button mono" onClick={() => setSelectedEvidence(item.evidence_id)}>{item.evidence_id.slice(0, 8)}…</button><span className="table-subtext evidence-preview">{item.evidence_preview}</span></td><td><strong>{item.job_title}</strong><span className="table-subtext mono">{item.job_id.slice(0, 8)}…</span></td><td>{item.source}<span className="table-subtext">{titleCase(item.source_type)}</span></td><td>{item.job_location}</td><td>{item.enrichment_present ? <span className="status-badge status-badge--enriched">Enriched</span> : <span className="status-badge">Source only</span>}{item.enrichment_present && <span className="table-subtext">{item.enrichment_model}</span>}</td><td><span>{item.related_hiring_signals.length} hiring signals</span><span className="table-subtext">{item.related_technology_observation_count} technology observations · {item.related_technology_signals.length} technology signals</span></td><td>{formatDate(item.captured_at)}</td></tr>)}</tbody></table></div><div className="pagination"><span>Showing {records.data.offset + 1}–{records.data.offset + records.data.returned_count} of {records.data.total}</span><div><button disabled={records.data.offset === 0} onClick={() => setFilters({ ...filters, offset: Math.max(0, filters.offset - filters.limit) })}>Previous</button><button disabled={records.data.offset + records.data.returned_count >= records.data.total} onClick={() => setFilters({ ...filters, offset: filters.offset + filters.limit })}>Next</button></div></div></>}
    </Panel>
    {selectedEvidence && <EvidenceDetailPanel evidenceId={selectedEvidence} onClose={() => setSelectedEvidence(null)} />}
  </div>;
}
