from backend.app.application.technology.models import TechnologyCategory


_ALIASES = {
    "amazon web services": "AWS",
    "aws": "AWS",
    "airflow": "Airflow",
    "angular.js": "Angular",
    "angularjs": "Angular",
    "apache flink": "Flink",
    "apache kafka": "Kafka",
    "apache spark": "Spark",
    "c sharp": "C#",
    "c#": "C#",
    "c plus plus": "C++",
    "c++": "C++",
    "databricks": "Databricks",
    "docker": "Docker",
    "excel": "Excel",
    "elasticsearch": "Elasticsearch",
    "flink": "Flink",
    "gradle": "Gradle",
    "google cloud platform": "Google Cloud",
    "gcp": "Google Cloud",
    "hadoop": "Hadoop",
    "java": "Java",
    "javascript": "JavaScript",
    "jenkins": "Jenkins",
    "kubernetes": "Kubernetes",
    "kafka": "Kafka",
    "linux": "Linux",
    "maven": "Maven",
    "microsoft azure": "Microsoft Azure",
    "ms excel": "Excel",
    "microsoft excel": "Excel",
    "mongo db": "MongoDB",
    "mongodb": "MongoDB",
    "mysql": "MySQL",
    "oracle": "Oracle",
    ".net": ".NET",
    "dotnet": ".NET",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "python": "Python",
    "react.js": "React",
    "reactjs": "React",
    "redis": "Redis",
    "sas": "SAS",
    "scala": "Scala",
    "selenium": "Selenium",
    "sql": "SQL",
    "snowflake": "Snowflake",
    "spark sql": "Spark",
    "spring boot": "Spring",
    "spring framework": "Spring",
    "spring mvc": "Spring",
    "tableau": "Tableau",
    "teradata": "Teradata",
    "terraform": "Terraform",
    "typescript": "TypeScript",
    "vba": "VBA",
}

_CATEGORIES = {
    "AWS": TechnologyCategory.CLOUD_PLATFORM,
    "Airflow": TechnologyCategory.DATA_ENGINEERING,
    "Angular": TechnologyCategory.OTHER,
    "C#": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "C++": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "Databricks": TechnologyCategory.DATA_ENGINEERING,
    "Docker": TechnologyCategory.DEVOPS_INFRASTRUCTURE,
    "Elasticsearch": TechnologyCategory.DATABASE,
    "Excel": TechnologyCategory.ANALYTICS_STATISTICAL_TOOL,
    "Flink": TechnologyCategory.DATA_ENGINEERING,
    "Gradle": TechnologyCategory.OTHER,
    "Google Cloud": TechnologyCategory.CLOUD_PLATFORM,
    "Hadoop": TechnologyCategory.DATA_PLATFORM,
    "Java": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "JavaScript": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "Jenkins": TechnologyCategory.DEVOPS_INFRASTRUCTURE,
    "Kubernetes": TechnologyCategory.DEVOPS_INFRASTRUCTURE,
    "Kafka": TechnologyCategory.DATA_PLATFORM,
    "Linux": TechnologyCategory.DEVOPS_INFRASTRUCTURE,
    "Maven": TechnologyCategory.OTHER,
    "Microsoft Azure": TechnologyCategory.CLOUD_PLATFORM,
    "MongoDB": TechnologyCategory.DATABASE,
    "MySQL": TechnologyCategory.DATABASE,
    ".NET": TechnologyCategory.OTHER,
    "Oracle": TechnologyCategory.DATABASE,
    "Power BI": TechnologyCategory.BI_VISUALIZATION,
    "PostgreSQL": TechnologyCategory.DATABASE,
    "Python": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "React": TechnologyCategory.OTHER,
    "Redis": TechnologyCategory.DATABASE,
    "SAS": TechnologyCategory.ANALYTICS_STATISTICAL_TOOL,
    "Scala": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "Selenium": TechnologyCategory.OTHER,
    "Snowflake": TechnologyCategory.DATA_PLATFORM,
    "SQL": TechnologyCategory.DATABASE,
    "Spark": TechnologyCategory.DATA_ENGINEERING,
    "Spring": TechnologyCategory.OTHER,
    "Tableau": TechnologyCategory.BI_VISUALIZATION,
    "Teradata": TechnologyCategory.DATA_PLATFORM,
    "Terraform": TechnologyCategory.DEVOPS_INFRASTRUCTURE,
    "TypeScript": TechnologyCategory.PROGRAMMING_LANGUAGE,
    "VBA": TechnologyCategory.PROGRAMMING_LANGUAGE,
}


def normalize_technology(value: str) -> str:
    compact = " ".join(value.strip().split())
    return _ALIASES.get(compact.casefold(), compact)


def categorize_technology(value: str) -> TechnologyCategory:
    return _CATEGORIES.get(value, TechnologyCategory.OTHER)
