import type { HiringAnalytics, JobDetail, JobListResponse, OrganizationSummary, SignalsResponse } from "../types/hiring";

const references = [{ job_id: "job-1", evidence_id: "evidence-1" }];
const geographic = { organization: "Wells Fargo", total_jobs: 1, by_country: [{ value: "US", job_count: 1, percentage_of_total: 100, contributing_records: references }], by_state_region: [{ value: "NC", job_count: 1, percentage_of_total: 100, contributing_records: references }], by_city: [{ value: "Charlotte", job_count: 1, percentage_of_total: 100, contributing_records: references }], contributing_records: references };
const capability = { organization: "Wells Fargo", classified_job_count: 1, capabilities: [{ capability: "Data & Analytics", job_count: 1, percentage_of_classified_jobs: 100, contributing_records: references }], contributing_records: references };
const seniority = { organization: "Wells Fargo", total_jobs: 1, jobs_with_seniority: 1, distribution: [{ seniority_level: "senior" as const, job_count: 1, percentage_of_jobs_with_seniority: 100, contributing_records: references }], leadership_job_count: 0, leadership_percentage: 0, leadership_contributing_records: [], contributing_records: references };
const trend = { organization: "Wells Fargo", granularity: "weekly" as const, observation_start: "2026-08-01", observation_end: "2026-08-20", buckets: [{ bucket_start: "2026-08-17", job_count: 1, contributing_records: references }], contributing_records: references };

export const summaryFixture: OrganizationSummary = { organization: "Wells Fargo", total_observed_jobs: 1, jobs_with_evidence: 1, evidence_coverage: 100, observation_start: "2026-08-01", observation_end: "2026-08-20", latest_collection_run: null, enriched_job_count: 1, enrichment_coverage: 100, signal_count: 0, generated_at: "2026-08-21T12:00:00Z", geographic, capability, seniority, trend };
export const analyticsFixture: HiringAnalytics = { snapshot: { organization: "Wells Fargo", total_active_jobs: 1, jobs_with_capability_classification: 1, jobs_with_seniority: 1, jobs_with_location: 1, generated_at: "2026-08-21T12:00:00Z", observation_start: "2026-08-01", observation_end: "2026-08-20", contributing_records: references }, geographic, capability, seniority, daily_trend: { ...trend, granularity: "daily" }, weekly_trend: trend };
export const signalsFixture: SignalsResponse = { organization: "Wells Fargo", generated_at: "2026-08-21T12:00:00Z", items: [], returned_count: 0 };
export const jobFixture = { job_id: "job-1", organization: "Wells Fargo", source_job_id: "R-1", title: "Senior Analytics Consultant", description: "Use Python for analytics.", location: "Charlotte, NC", country: "US", business_unit: null, capability_classifications: ["Data & Analytics"], skills: [], technologies: [], seniority_level: "senior" as const, is_leadership: false, posted_date: "2026-08-20", closing_date: null, employment_type: "full_time" as const, source_url: "https://example.test/job", evidence_id: "evidence-1" };
export const jobsFixture: JobListResponse = { items: [jobFixture], total: 1, limit: 10, offset: 0, returned_count: 1 };
export const detailFixture: JobDetail = { job: jobFixture, evidence: { evidence_id: "evidence-1", source_url: "https://example.test/job", source_type: "career_site", source_title: jobFixture.title, retrieved_at: "2026-08-20T12:00:00Z", source_excerpt: "Use Python for analytics.", raw_reference: "career:R-1", collector_identity: "fixture", provenance_metadata: {} }, enrichment: null };
